config/routes.rb
Rails.application.routes.draw do
  resources :customers

  root 'home#index'

  get '/logout' => 'home#logout'

  get '/search_customers' => 'customers#search'

  get '/results' => 'customers#result'

  get '/new_user' => 'customers#new_user'

  post 'create_useradmin' => 'customers#create_user'

  post 'create_admin' => 'home#create_admin'
  post 'create_user' => 'home#create_user'
  get 'user' => 'home#user'
  get 'user/new' => 'home#new_user'

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  mount_uploader :pdffile, FileUploader
  mount_uploader :pdffile2, File2Uploader
  mount_uploader :pdffile3, File3Uploader
  mount_uploader :pdffile4, File4Uploader
  mount_uploader :pdffile5, File5Uploader
  mount_uploader :pdffile6, File6Uploader
  mount_uploader :pdffile7, File7Uploader
  mount_uploader :pdffile8, File8Uploader
  mount_uploader :pdffile9, File9Uploader
  mount_uploader :pdffile10, File10Uploader

end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :file, FileUploader

end

app/models/useradmin.rb
class Useradmin < ActiveRecord::Base

  validates_confirmation_of :password

  validates :username, :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json

  def new_user
    @user = Useradmin.new
  end

  def create_user
    @user = Useradmin.new(user_params)
    if @user.save
      redirect_to customers_path, notice: 'User was successfully created.'
    else
      render :new_user
    end
  end

  def index
    if session[:admin] == "accepted"
      @level = session[:level]
      @customers = Customer.all
    else
      redirect_to root_path
    end
  end

  def search
    @q = Customer.search(params[:q])

  end

  def result
    @q = Customer.search(params[:q])
    @q = @q.result(distinct: true)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    if session[:admin] == "accepted"

    else
      redirect_to root_path
    end
  end

  # GET /customers/new
  def new
    if session[:admin] == "accepted"
      @customer = Customer.new
    else
      redirect_to root_path
    end
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email, :phone_number, :pdffile, :pdffile2, :pdffile3,
                                       :pdffile4, :pdffile5, :pdffile6, :pdffile7, :pdffile8, :pdffile9, :pdffile10)
    end

    def user_params
      params.require(:useradmin).permit(:username, :password, :password_confirmation, :level)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if session[:admin] == "accepted"
      redirect_to customers_path
    end
  end

  def logout
    session[:admin] = nil
    session[:level] = nil
    redirect_to root_path
  end

  def create_admin
    asd = Useradmin.where(username: params[:username], password: params[:password]).first
    if asd
      session[:admin] = "accepted"

      if asd.level == 1
        session[:level] = "level1"
      elsif asd.level == 2
        session[:level] = "level2"
      elsif asd.level == 3
        session[:level] = "level3"
      end

      redirect_to customers_path
    else
      flash[:alert] = "Username or password incorrect!"
      render :index
    end
  end

  def user
    if session[:admin] == "accepted"

    else
      redirect_to root_path
    end
  end

  def new_user
    if session[:admin] == "accepted"

    else
      redirect_to root_path
    end
  end

  def create_user
    a = User.new(first_name: params[:first_name], last_name: params[:last_name],
                 email: params[:email], phone_number: params[:phone_number], store_number: params[:store_number],
                 file: params[:file])
    a.save!
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :pdffile %><br>
    <%= f.file_field :pdffile %>
  </div>
    <div class="field">
      <%= f.label :pdffile2 %><br>
      <%= f.file_field :pdffile2 %>
    </div>
    <div class="field">
      <%= f.label :pdffile3 %><br>
      <%= f.file_field :pdffile3 %>
    </div>
    <div class="field">
      <%= f.label :pdffile4 %><br>
      <%= f.file_field :pdffile4 %>
    </div>
    <div class="field">
      <%= f.label :pdffile5 %><br>
      <%= f.file_field :pdffile5 %>
    </div>
    <div class="field">
      <%= f.label :pdffile6 %><br>
      <%= f.file_field :pdffile6 %>
    </div>
    <div class="field">
      <%= f.label :pdffile7 %><br>
      <%= f.file_field :pdffile7 %>
    </div>
    <div class="field">
      <%= f.label :pdffile8 %><br>
      <%= f.file_field :pdffile8 %>
    </div>
    <div class="field">
      <%= f.label :pdffile9 %><br>
      <%= f.file_field :pdffile9 %>
    </div>
    <div class="field">
      <%= f.label :pdffile10 %><br>
      <%= f.file_field :pdffile10 %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.phone_number %></td>
        <td><%= link_to customer.pdffile_identifier, customer.pdffile.url %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/new_user.html.erb
<%= form_for @user, :url => {:controller => "customers", :action => "create_user"} do |f| %>

    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>

    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="field">
      <%= f.label "please select the level of admin" %><br>
      <%= f.select :level, [ [1,1], [2,2], [3,3]] %>
    </div>

    <div class="field">

      <p>
        level 1: super user have all rights
      </p>

      <p>
        level 2: super user have all rights, except to create new user
      </p>

      <p>
        level 3: can only view customers
      </p>

    </div>

    <%= f.submit %>

<% end %>

<%= link_to 'Back', customers_path %>

app/views/customers/result.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<%= link_to 'New Customer', new_customer_path %>

<%= link_to 'Search', '/search_customers' %>

<%= link_to 'Show All', customers_path %>

<table>
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Phone number</th>
    <th>Data</th>
    <th>Data2</th>
    <th>Data3</th>
    <th>Data4</th>
    <th>Data5</th>
    <th>Data6</th>
    <th>Data7</th>
    <th>Data8</th>
    <th>Data9</th>
    <th>Data10</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @q.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.phone_number %></td>

        <% if customer.pdffile.url == nil %>
            <td>N/A</td>
        <% else %>

            <td><%= link_to customer.pdffile_identifier, customer.pdffile.url %></td>

        <% end %>

        <% if customer.pdffile2.url == nil %>
            <td>N/A</td>
        <% else %>
            <td><%= link_to customer.pdffile2_identifier, customer.pdffile2.url %></td>
        <% end %>


        <% if customer.pdffile3.url == nil %>
            <td>N/A</td>
        <% else %>
            <td><%= link_to customer.pdffile3_identifier, customer.pdffile3.url %></td>
        <% end %>

        <% if customer.pdffile4.url == nil %>
            <td>N/A</td>
        <% else %>
            <td><%= link_to customer.pdffile4_identifier, customer.pdffile4.url %></td>
        <% end %>

        <% if customer.pdffile5.url == nil %>
            <td>N/A</td>
        <% else %>
            <td><%= link_to customer.pdffile5_identifier, customer.pdffile5.url %></td>
        <% end %>

        <% if customer.pdffile6.url == nil %>
            <td>N/A</td>
        <% else %>
            <td><%= link_to customer.pdffile6_identifier, customer.pdffile6.url %></td>
        <% end %>

        <% if customer.pdffile7.url == nil %>
            <td>N/A</td>
        <% else %>
            <td><%= link_to customer.pdffile7_identifier, customer.pdffile7.url %></td>
        <% end %>

        <% if customer.pdffile8.url == nil %>
            <td>N/A</td>
        <% else %>
            <td><%= link_to customer.pdffile8_identifier, customer.pdffile8.url %></td>
        <% end %>

        <% if customer.pdffile9.url == nil %>
            <td>N/A</td>
        <% else %>
            <td><%= link_to customer.pdffile9_identifier, customer.pdffile9.url %></td>
        <% end %>

        <% if customer.pdffile10.url == nil %>
            <td>N/A</td>
        <% else %>

            <td><%= link_to customer.pdffile10_identifier, customer.pdffile10.url %></td>
        <% end %>

        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/customers/search.html.erb
<%= search_form_for @q , url: results_path do |f| %>

    <%= f.search_field :first_name_cont, class: "form-control" %>
    <%= f.submit %>

<% end %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @customer.phone_number %>
</p>

<p>
  <strong>data:</strong>
  <%= link_to @customer.pdffile_identifier, @customer.pdffile.url %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/home/index.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>


<h1>JafferyCMS</h1>


<%= form_tag create_admin_path do %>

    <%= label_tag :username %>
    <%= text_field_tag :username %>

    <%= label_tag :password %>
    <%= password_field_tag :password %>

    <%= submit_tag "Sign in" %>


<% end %>

app/views/home/new_user.html.erb
<%= form_tag create_user_path do %>

    <%= label_tag :first_name %>
    <%= text_field_tag :first_name %>

    <%= label_tag :last_name %>
    <%= text_field_tag :last_name %>

    <%= label_tag :email %>
    <%= text_field_tag :email %>

    <%= label_tag :phone_number %>
    <%= text_field_tag :phone_number %>

    <%= label_tag :store_number %>
    <%= text_field_tag :store_number %>

    <%= label_tag 'user information' %>
    <%= file_field_tag :file %>

    <%= submit_tag "create" %>


<% end %>

app/views/home/user.html.erb
<%= link_to "new", user_new_path, :class => "dropdown-toggle" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jafferycms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>